[build]
  publish = "/"
  functions = "netlify/functions"
  command = "npm install && npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Abilita l'estensione Netlify Blobs
[template.environment]
  NETLIFY_BLOBS_ENABLED = "true"
