[build]
  publish = "/"
  functions = "netlify/functions"
  command = "npm install && npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Configurazione delle funzionalità Netlify
[functions]
  # Attiva esplicitamente Netlify Blobs per le funzioni
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[build.environment]
  # Abilita esplicitamente Netlify Blobs
  NETLIFY_BLOBS_ENABLED = "true"
