build:
  publish: "/"
  functions: "netlify/functions"
  command: "npm ci && npm run build"
  environment:
    NETLIFY_BLOBS_ENABLED: "true"

functions:
  '*':
    node_bundler: esbuild
    
redirects:
  - from: /api/*
    to: /.netlify/functions/:splat
    status: 200

plugins:
  - package: '@netlify/plugin-functions-install-core'
  - package: '@netlify/blobs'
    inputs:
      enabled: true
