build:
  publish: "/"
  functions: "netlify/functions"
  command: "cd netlify/functions && npm install"

functions:
  '*':
    node_bundler: esbuild
    
redirects:
  - from: /api/*
    to: /.netlify/functions/:splat
    status: 200
